config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  #root 'tasks#index'
  resources :tasks
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  namespace :admin do 
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :name, :detail, :deadline, presence: true

    enum priority: {  Low: 0, Medium: 1, High: 2 }

    scope :search, -> (param) { where("name LIKE ?" , "%#{param}%") }

    scope :search_status, -> (param) { where(status: param) }
end

app/models/user.rb
class User < ApplicationRecord
    before_validation { email.downcase! }
    validates :username, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                        format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    has_secure_password
    validates :password, length: { minimum: 6 }
    has_many :tasks, dependent: :delete_all
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update destroy ]
    skip_before_action :login_required, only: [ :new, :create]

    def index
        redirect_to tasks_path, notice: 'only the administrator can access it' if current_user.is_admin != true
        @users = User.all.where.not(id: current_user.id)
    end
    
    def show
        @tasks = @user.tasks.all
    end
  
    def new
      if current_user&.is_admin 
        @user = User.new
      elsif current_user ==nil
        @user = User.new
      else
        redirect_to tasks_path
      end
    end
  
    def edit
    end
  
    def create
      @user = User.new(user_params)
      
      respond_to do |format|
        if @user.save
          if current_user == nil 
            session[:user_id] = @user.id
          end
          format.html { redirect_to tasks_path, notice: "User was successfully created." }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to admin_users_path, notice: "Changed user information" }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
    def set_user
      @user = User.find(params[:id])
    end
  
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :is_admin)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required
    private
    def login_required
        redirect_to new_session_path unless current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to tasks_path
    else
      flash.now[:danger] = 'I failed to login'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'logged out'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    #puts "ici la valeur de select #{params[:search_status].to_s.strip.empty?}"
    if params[:search] 
      @tasks = Task.search(params[:search])
      if !params[:search_status].to_s.strip.empty?
        @tasks = @tasks.select{ |task| task.status == params[:search_status] }
      end
    elsif params[:search_status]
      @tasks = Task.search_status(params[:search_status])
    elsif params[:sort_priority]
      @tasks = current_user.tasks.order("priority desc")
    else
      if params[:sort_expired]
        @sort_expired = params[:sort_expired]
        @tasks = current_user.tasks.order("deadline desc")
      else
        @tasks = current_user.tasks.order("created_at desc")
      end
    end
    @tasks = Kaminari.paginate_array(@tasks).page(params[:page]).per(5)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @tasks = @user.tasks.all
  end
  
  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :detail, :deadline, :status, :search, :search_status, :priority)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to new_session_path
        else
            render :new, notice: 'Account creation fails'
        end
    end

    def show
        @user = User.find(params[:id])
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user.present?
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_footer.html.erb
<footer>
    <p> Dive Into Code &copy; 2021 Instagram App | Design by Gyll-christ DOKO ALFA</p>
</footer>

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user], local: true) do |form| %>
<% if
user.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(user.errors.count, "error") %> prohibited this user from being
    saved:
  </h2>

  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= form.label :username %> <%= form.text_field :username %>
</div>
<div class="field">
  <%= form.label :email %> <%= form.email_field :email %>
</div>

<div class="field">
  <%= form.label :password %> <%= form.password_field :password %>
</div>
<div class="field">
  <%= form.label :password_confirmation %> <%=
  form.password_field:password_confirmation %>
</div>
<div class="field my-2">
  <%= form.label "make admin"%>
  <%= form.check_box :is_admin %>
</div>

<% if action_name == "edit" %>
<div  ><%= form.submit "Update" %></div>
<% else %>
<div ><%= form.submit "Signup" %></div>

<% end %> <% end %>

app/views/admin/users/_header.html.erb
<header>
    <nav class="navbar navbar-light bg-light p-3">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">Instagram Clone App</span>
            <% if logged_in? %>
            <div class="">

                <%= link_to 'View all posts', posts_path , class: "btn btn-outline-secondary"%>
                <%= link_to 'Publish', new_post_path , class: "btn btn-outline-primary"%>
            </div>
            <div>
                <%= link_to "Profile", user_path(current_user.id) , class: "btn btn-primary text-light"%>
                <%= link_to "Logout", session_path(current_user.id), method: :delete , class: "btn btn-danger text-light" %>
            </div>
            <% else %>
            <div>

                <%= link_to "Sign up", new_user_path , class: "btn btn-outline-primary mx-3", style: "float: right;" %>
                <%= link_to "Login", new_session_path, class: "btn btn-success text-light" %>

            </div>
            <% end %>
        </div>
    </nav>
</header>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %> 
<%= link_to 'Show', edit_admin_user_url(@user) %> | 
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
      <th>Task count</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <td>
        <%= link_to 'Destroy', admin_user_path(user), method: :delete, data: {
        confirm: 'Are you sure?' } %>
      </td>
      <td style="padding-left: 30px"><%=user.tasks.count%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container text-center">
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  
  <% if current_user.is_admin %>
    <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-warning" %>
  <% end %>
  
   | <%=
  link_to 'Back', tasks_path , class: "btn btn-danger"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Everyleaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |key, value| %> 
    <%= content_tag(:div, value, class: "#{key}") %> 
    <% end %>

    <% if logged_in? %> 
    <%= link_to "Profile", user_path(current_user.id) %> 
    <%= link_to "Logout", session_path(current_user.id), method: :delete %> 
    <% else %> 
    <%= link_to "Sign up", new_user_path %> 
    <%= link_to "Login", new_session_path %> 
    <% end %> 
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_field :deadline %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ['unstarted', 'in progress', 'completed'] %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, ['Low', 'Medium', 'High'] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<h4>Search by title: </h4>
  <%= form_tag(tasks_path, method: :get) do |f| %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= select_tag(:search_status, options_for_select(Task.distinct.pluck(:status).uniq ,:selected =>params[:search_status]), include_blank: true  )%>   
     <%= submit_tag("Search") %>
  <% end %>

  <h4>Search by status: </h4>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Detail</th>
      <th>Status</th>
      <th>Deadline</th>
      <th>Priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <%= paginate @tasks %>
    <% @tasks.each do |task| %>
      <tr>
        <td class="task_row"><%= task.name %></td>  
        <td><%= task.detail %></td>
        <td><%= task.status %></td>
        <td><%= task.deadline %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if @sort_expired %>
  <%= link_to "Back", tasks_path %>
<% else %>
  <%= link_to " sort by end deadline", tasks_path(sort_expired: "true") %>
  <%= link_to " sort by priority", tasks_path(sort_priority: "true") %>
<% end %>
<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @task.detail %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_footer.html.erb
<footer>
    <p> Dive Into Code &copy; 2021 Instagram App | Design by Gyll-christ DOKO ALFA</p>
</footer>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %> <% if user.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(user.errors.count, "error") %> prohibited this user from being
    saved:
  </h2>

  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= form.label :username %> <%= form.text_field :username "%>
</div>
<div class="field">
  <%= form.label :email %> <%= form.email_field :email "%>
</div>

<div class="field">
  <%= form.label :password %> <%= form.password_field :password %>
</div>
<div class="field">
  <%= form.label :password_confirmation %> <%= form.password_field  :password_confirmation %>
</div>

<div ><%= form.submit "Signup" %></div>
<% end %>

app/views/users/_header.html.erb
<header>
    <nav class="navbar navbar-light bg-light p-3">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">Instagram Clone App</span>
            <% if logged_in? %>
            <div class="">

                <%= link_to 'View all posts', posts_path , class: "btn btn-outline-secondary"%>
                <%= link_to 'Publish', new_post_path , class: "btn btn-outline-primary"%>
            </div>
            <div>
                <%= link_to "Profile", user_path(current_user.id) , class: "btn btn-primary text-light"%>
                <%= link_to "Logout", session_path(current_user.id), method: :delete , class: "btn btn-danger text-light" %>
            </div>
            <% else %>
            <div>

                <%= link_to "Sign up", new_user_path , class: "btn btn-outline-primary mx-3", style: "float: right;" %>
                <%= link_to "Login", new_session_path, class: "btn btn-success text-light" %>

            </div>
            <% end %>
        </div>
    </nav>
</header>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign up</h1> 

<% if @user.errors.any? %> 
<div id="error_explanation"> 
<h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2> 
<ul> 
<% @user.errors.full_messages.each do |message| %> 
<li><%= message %></li> 
<% end %> 
</ul> 
</div> 
<% end %> 

 <%= form_with(model: @user, local: true) do |f| %> 
 <%= f.label :username %> 
 <%= f.text_field :username %> 
 <%= f.label :email %> 
 <%= f.email_field :email %> 
 <%= f.label :password %> 
 <%= f.password_field :password %> 
 <%= f.label :password_confirmation %> 
 <%= f.password_field :password_confirmation %> 
 <%= f.submit "Create my account" %> 
 <% end %>

app/views/users/show.html.erb
<h1><%= @user.username %> page of</h1>
<p>E-mail address:<%= @user.email %></p>

<h2> <%= @user.username %>' tasks: </h2>
<% if @task %>
<% @tasks.each do |task| %>
    <tr>
      <td class="task_row"><%= task.name %></td>  
      <td><%= task.detail %></td>
      <td><%= task.status %></td>
      <td><%= task.deadline %></td>
      <td><%= task.priority %></td>
    </tr>
  <% end %>
</tbody>
</table>
<%= link_to "Back", tasks_path %>
<% else %>
<p> No tasks for this user </p>
<% end %>